name: flutter_xp
description: Flutter_XP.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.4.1
  flutter_drawing_board:
    git:
      url: https://github.com/AlphaPolo/flutter_drawing_board.git
      ref: msPainter
  flutter_inappwebview: ^6.0.0
  flutter_markdown: ^0.7.3+1
#  firebase_core: ^3.8.1
#  firebase_analytics: ^11.3.0
  collection: ^1.17.1
  cupertino_icons: ^1.0.2
  dotted_border: ^2.1.0
  intl: ^0.19.0
  provider: ^6.1.2
  r_dart_library: 0.4.1
  url_launcher: ^6.3.0
#  pointer_interceptor: ^0.10.1+2

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
dependency_overrides:
  flutter_svg: ^1.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/btn_back.png
  - assets/images/btn_forward.png
  - assets/images/btn_start.png
  - assets/images/icon_audio_16.png
  - assets/images/icon_cd_48.png
  - assets/images/icon_checklist_32.png
  - assets/images/icon_computer_16.png
  - assets/images/icon_computer_32.png
  - assets/images/icon_connect_to_32.png
  - assets/images/icon_control_panel_16.png
  - assets/images/icon_control_panel_32.png
  - assets/images/icon_dangerous_16.png
  - assets/images/icon_disk_48.png
  - assets/images/icon_document_32.png
  - assets/images/icon_dropdown_16.png
  - assets/images/icon_email_32.png
  - assets/images/icon_favorites_32.png
  - assets/images/icon_folder_32.png
  - assets/images/icon_folder_48.png
  - assets/images/icon_folder_up.png
  - assets/images/icon_fortune_wheel_48.png
  - assets/images/icon_hexagon_defense_48.png
  - assets/images/icon_hexagon_jubeat_48.png
  - assets/images/icon_hexagon_tos_48.png
  - assets/images/icon_history_32.png
  - assets/images/icon_home_32.png
  - assets/images/icon_ie_paper_16.png
  - assets/images/icon_internet_32.png
  - assets/images/icon_l_game_48.png
  - assets/images/icon_listen_music_learn_language_48.png
  - assets/images/icon_mail_32.png
  - assets/images/icon_media_player_32.png
  - assets/images/icon_msn_32.png
  - assets/images/icon_my_documents_16.png
  - assets/images/icon_my_documents_32.png
  - assets/images/icon_my_music_32.png
  - assets/images/icon_my_network_16.png
  - assets/images/icon_my_pictures_32.png
  - assets/images/icon_my_recent_documents_32.png
  - assets/images/icon_notepad_16.png
  - assets/images/icon_notepad_32.png
  - assets/images/icon_paint_32.png
  - assets/images/icon_print_and_fax_32.png
  - assets/images/icon_printer_32.png
  - assets/images/icon_program_asset_32.png
  - assets/images/icon_programs_manager_16.png
  - assets/images/icon_refresh_32.png
  - assets/images/icon_rogue_horizontal_defense_48.png
  - assets/images/icon_run_32.png
  - assets/images/icon_search_32.png
  - assets/images/icon_share_documents_16.png
  - assets/images/icon_solitaire_32.png
  - assets/images/icon_stop_32.png
  - assets/images/icon_support_32.png
  - assets/images/icon_tetris_puyo_48.png
  - assets/images/icon_uno_48.png
  - assets/images/icon_usb_16.png
  - assets/images/icon_user_32.png
  - assets/images/icon_view_info_16.png
  - assets/images/icon_weiqi_48.png
  - assets/images/icon_winamp_32.png
  - assets/images/icon_windows_flag.png
  - assets/images/img_windowsXP.png
  - assets/images/minesweeper/checked.png
  - assets/images/minesweeper/dead.png
  - assets/images/minesweeper/digit-.png
  - assets/images/minesweeper/digit0.png
  - assets/images/minesweeper/digit1.png
  - assets/images/minesweeper/digit2.png
  - assets/images/minesweeper/digit3.png
  - assets/images/minesweeper/digit4.png
  - assets/images/minesweeper/digit5.png
  - assets/images/minesweeper/digit6.png
  - assets/images/minesweeper/digit7.png
  - assets/images/minesweeper/digit8.png
  - assets/images/minesweeper/digit9.png
  - assets/images/minesweeper/flag.png
  - assets/images/minesweeper/icon_mine_32.png
  - assets/images/minesweeper/mine-ceil.png
  - assets/images/minesweeper/mine-death.png
  - assets/images/minesweeper/misflagged.png
  - assets/images/minesweeper/ohh.png
  - assets/images/minesweeper/open1.png
  - assets/images/minesweeper/open2.png
  - assets/images/minesweeper/open3.png
  - assets/images/minesweeper/open4.png
  - assets/images/minesweeper/open5.png
  - assets/images/minesweeper/open6.png
  - assets/images/minesweeper/open7.png
  - assets/images/minesweeper/open8.png
  - assets/images/minesweeper/question.png
  - assets/images/minesweeper/smile.png
  - assets/images/minesweeper/win.png
  - assets/images/painter/print_tools_0.png
  - assets/images/painter/print_tools_1.png
  - assets/images/painter/print_tools_10.png
  - assets/images/painter/print_tools_11.png
  - assets/images/painter/print_tools_12.png
  - assets/images/painter/print_tools_13.png
  - assets/images/painter/print_tools_14.png
  - assets/images/painter/print_tools_15.png
  - assets/images/painter/print_tools_2.png
  - assets/images/painter/print_tools_3.png
  - assets/images/painter/print_tools_4.png
  - assets/images/painter/print_tools_5.png
  - assets/images/painter/print_tools_6.png
  - assets/images/painter/print_tools_7.png
  - assets/images/painter/print_tools_8.png
  - assets/images/painter/print_tools_9.png
  - assets/images/solitaire/2C.png
  - assets/images/solitaire/2D.png
  - assets/images/solitaire/2H.png
  - assets/images/solitaire/2S.png
  - assets/images/solitaire/3C.png
  - assets/images/solitaire/3D.png
  - assets/images/solitaire/3H.png
  - assets/images/solitaire/3S.png
  - assets/images/solitaire/4C.png
  - assets/images/solitaire/4D.png
  - assets/images/solitaire/4H.png
  - assets/images/solitaire/4S.png
  - assets/images/solitaire/5C.png
  - assets/images/solitaire/5D.png
  - assets/images/solitaire/5H.png
  - assets/images/solitaire/5S.png
  - assets/images/solitaire/6C.png
  - assets/images/solitaire/6D.png
  - assets/images/solitaire/6H.png
  - assets/images/solitaire/6S.png
  - assets/images/solitaire/7C.png
  - assets/images/solitaire/7D.png
  - assets/images/solitaire/7H.png
  - assets/images/solitaire/7S.png
  - assets/images/solitaire/8C.png
  - assets/images/solitaire/8D.png
  - assets/images/solitaire/8H.png
  - assets/images/solitaire/8S.png
  - assets/images/solitaire/9C.png
  - assets/images/solitaire/9D.png
  - assets/images/solitaire/9H.png
  - assets/images/solitaire/9S.png
  - assets/images/solitaire/AC.png
  - assets/images/solitaire/AD.png
  - assets/images/solitaire/AH.png
  - assets/images/solitaire/AS.png
  - assets/images/solitaire/JC.png
  - assets/images/solitaire/JD.png
  - assets/images/solitaire/JH.png
  - assets/images/solitaire/JS.png
  - assets/images/solitaire/KC.png
  - assets/images/solitaire/KD.png
  - assets/images/solitaire/KH.png
  - assets/images/solitaire/KS.png
  - assets/images/solitaire/QC.png
  - assets/images/solitaire/QD.png
  - assets/images/solitaire/QH.png
  - assets/images/solitaire/QS.png
  - assets/images/solitaire/TC.png
  - assets/images/solitaire/TD.png
  - assets/images/solitaire/TH.png
  - assets/images/solitaire/TS.png
  - assets/images/solitaire/joker.png
  - assets/images/transparent_background.jpg
  - assets/images/painter/
  - assets/images/solitaire/
  - assets/markdown/
flr:
  core_version: 3.2.0
  dartfmt_line_length: 80
  assets:
  - assets/images
  fonts: []
