// IT IS GENERATED BY FLR - DO NOT MODIFY BY HAND
        // YOU CAN GET MORE DETAILS ABOUT FLR FROM:
        // - https://github.com/Fly-Mix/flr-cli
        // - https://github.com/Fly-Mix/flr-vscode-extension
        // - https://github.com/Fly-Mix/flr-as-plugin
        //

        // ignore_for_file: depend_on_referenced_packages

        // ignore: unused_import
        import 'package:flutter/widgets.dart';
        // ignore: unused_import
        import 'package:flutter/services.dart' show rootBundle;
        // ignore: unused_import
        import 'package:path/path.dart' as path;
        // ignore: unused_import
        import 'package:flutter_svg/flutter_svg.dart';
        // ignore: unused_import
        import 'package:r_dart_library/asset_svg.dart';
        
        /// This `R` class is generated and contains references to static asset resources.
        class R {
          /// package name: flutter_xp
          static const package = "flutter_xp";
        
          /// This `R.image` struct is generated, and contains static references to static non-svg type image asset resources.
          static const image = _R_Image();
        
          /// This `R.svg` struct is generated, and contains static references to static svg type image asset resources.
          static const svg = _R_Svg();
        
          /// This `R.text` struct is generated, and contains static references to static text asset resources.
          static const text = _R_Text();
        
          /// This `R.fontFamily` struct is generated, and contains static references to static font asset resources.
          static const fontFamily = _R_FontFamily();
        }
/// Asset resource’s metadata class.
      /// For example, here is the metadata of `packages/flutter_demo/assets/images/example.png` asset:
      /// - packageName：flutter_demo
      /// - assetName：assets/images/example.png
      /// - fileDirname：assets/images
      /// - fileBasename：example.png
      /// - fileBasenameNoExtension：example
      /// - fileExtname：.png
      class AssetResource {
        /// Creates an object to hold the asset resource’s metadata.
        const AssetResource(this.assetName, {this.packageName});
      
        /// The name of the main asset from the set of asset resources to choose from.
        final String assetName;
      
        /// The name of the package from which the asset resource is included.
        final String? packageName;
      
        /// The name used to generate the key to obtain the asset resource. For local assets
        /// this is [assetName], and for assets from packages the [assetName] is
        /// prefixed 'packages/<package_name>/'.
        String get keyName => packageName == null ? assetName : "packages/$packageName/$assetName";
      
        /// The file basename of the asset resource.
        String get fileBasename {
          final basename = path.basename(assetName);
          return basename;
        }
      
        /// The no extension file basename of the asset resource.
        String get fileBasenameNoExtension {
          final basenameWithoutExtension = path.basenameWithoutExtension(assetName);
          return basenameWithoutExtension;
        }
      
        /// The file extension name of the asset resource.
        String get fileExtname {
          final extension = path.extension(assetName);
          return extension;
        }
      
        /// The directory path name of the asset resource.
        String get fileDirname {
          var dirname = assetName;
          if (packageName != null) {
            final packageStr = "packages/$packageName/";
            dirname = dirname.replaceAll(packageStr, "");
          }
          final filenameStr = "$fileBasename/";
          dirname = dirname.replaceAll(filenameStr, "");
          return dirname;
        }
      }
// ignore: camel_case_types
      class _R_Image_AssetResource {
        const _R_Image_AssetResource();
      
  /// asset: assets/images/btn_back.png
      // ignore: non_constant_identifier_names
      final btn_back = const AssetResource("assets/images/btn_back.png", packageName: null);
  /// asset: assets/images/btn_forward.png
      // ignore: non_constant_identifier_names
      final btn_forward = const AssetResource("assets/images/btn_forward.png", packageName: null);
  /// asset: assets/images/btn_start.png
      // ignore: non_constant_identifier_names
      final btn_start = const AssetResource("assets/images/btn_start.png", packageName: null);
  /// asset: assets/images/icon_alian_48.png
      // ignore: non_constant_identifier_names
      final icon_alian_48 = const AssetResource("assets/images/icon_alian_48.png", packageName: null);
  /// asset: assets/images/icon_audio_16.png
      // ignore: non_constant_identifier_names
      final icon_audio_16 = const AssetResource("assets/images/icon_audio_16.png", packageName: null);
  /// asset: assets/images/icon_cd_48.png
      // ignore: non_constant_identifier_names
      final icon_cd_48 = const AssetResource("assets/images/icon_cd_48.png", packageName: null);
  /// asset: assets/images/icon_checklist_32.png
      // ignore: non_constant_identifier_names
      final icon_checklist_32 = const AssetResource("assets/images/icon_checklist_32.png", packageName: null);
  /// asset: assets/images/icon_computer_16.png
      // ignore: non_constant_identifier_names
      final icon_computer_16 = const AssetResource("assets/images/icon_computer_16.png", packageName: null);
  /// asset: assets/images/icon_computer_32.png
      // ignore: non_constant_identifier_names
      final icon_computer_32 = const AssetResource("assets/images/icon_computer_32.png", packageName: null);
  /// asset: assets/images/icon_connect_to_32.png
      // ignore: non_constant_identifier_names
      final icon_connect_to_32 = const AssetResource("assets/images/icon_connect_to_32.png", packageName: null);
  /// asset: assets/images/icon_control_panel_16.png
      // ignore: non_constant_identifier_names
      final icon_control_panel_16 = const AssetResource("assets/images/icon_control_panel_16.png", packageName: null);
  /// asset: assets/images/icon_control_panel_32.png
      // ignore: non_constant_identifier_names
      final icon_control_panel_32 = const AssetResource("assets/images/icon_control_panel_32.png", packageName: null);
  /// asset: assets/images/icon_dangerous_16.png
      // ignore: non_constant_identifier_names
      final icon_dangerous_16 = const AssetResource("assets/images/icon_dangerous_16.png", packageName: null);
  /// asset: assets/images/icon_disk_48.png
      // ignore: non_constant_identifier_names
      final icon_disk_48 = const AssetResource("assets/images/icon_disk_48.png", packageName: null);
  /// asset: assets/images/icon_document_32.png
      // ignore: non_constant_identifier_names
      final icon_document_32 = const AssetResource("assets/images/icon_document_32.png", packageName: null);
  /// asset: assets/images/icon_dropdown_16.png
      // ignore: non_constant_identifier_names
      final icon_dropdown_16 = const AssetResource("assets/images/icon_dropdown_16.png", packageName: null);
  /// asset: assets/images/icon_email_32.png
      // ignore: non_constant_identifier_names
      final icon_email_32 = const AssetResource("assets/images/icon_email_32.png", packageName: null);
  /// asset: assets/images/icon_favorites_32.png
      // ignore: non_constant_identifier_names
      final icon_favorites_32 = const AssetResource("assets/images/icon_favorites_32.png", packageName: null);
  /// asset: assets/images/icon_folder_32.png
      // ignore: non_constant_identifier_names
      final icon_folder_32 = const AssetResource("assets/images/icon_folder_32.png", packageName: null);
  /// asset: assets/images/icon_folder_48.png
      // ignore: non_constant_identifier_names
      final icon_folder_48 = const AssetResource("assets/images/icon_folder_48.png", packageName: null);
  /// asset: assets/images/icon_folder_up.png
      // ignore: non_constant_identifier_names
      final icon_folder_up = const AssetResource("assets/images/icon_folder_up.png", packageName: null);
  /// asset: assets/images/icon_fortune_wheel_48.png
      // ignore: non_constant_identifier_names
      final icon_fortune_wheel_48 = const AssetResource("assets/images/icon_fortune_wheel_48.png", packageName: null);
  /// asset: assets/images/icon_hexagon_defense_48.png
      // ignore: non_constant_identifier_names
      final icon_hexagon_defense_48 = const AssetResource("assets/images/icon_hexagon_defense_48.png", packageName: null);
  /// asset: assets/images/icon_hexagon_jubeat_48.png
      // ignore: non_constant_identifier_names
      final icon_hexagon_jubeat_48 = const AssetResource("assets/images/icon_hexagon_jubeat_48.png", packageName: null);
  /// asset: assets/images/icon_hexagon_tos_48.png
      // ignore: non_constant_identifier_names
      final icon_hexagon_tos_48 = const AssetResource("assets/images/icon_hexagon_tos_48.png", packageName: null);
  /// asset: assets/images/icon_history_32.png
      // ignore: non_constant_identifier_names
      final icon_history_32 = const AssetResource("assets/images/icon_history_32.png", packageName: null);
  /// asset: assets/images/icon_home_32.png
      // ignore: non_constant_identifier_names
      final icon_home_32 = const AssetResource("assets/images/icon_home_32.png", packageName: null);
  /// asset: assets/images/icon_ie_paper_16.png
      // ignore: non_constant_identifier_names
      final icon_ie_paper_16 = const AssetResource("assets/images/icon_ie_paper_16.png", packageName: null);
  /// asset: assets/images/icon_internet_32.png
      // ignore: non_constant_identifier_names
      final icon_internet_32 = const AssetResource("assets/images/icon_internet_32.png", packageName: null);
  /// asset: assets/images/icon_l_game_48.png
      // ignore: non_constant_identifier_names
      final icon_l_game_48 = const AssetResource("assets/images/icon_l_game_48.png", packageName: null);
  /// asset: assets/images/icon_listen_music_learn_language_48.png
      // ignore: non_constant_identifier_names
      final icon_listen_music_learn_language_48 = const AssetResource("assets/images/icon_listen_music_learn_language_48.png", packageName: null);
  /// asset: assets/images/icon_mail_32.png
      // ignore: non_constant_identifier_names
      final icon_mail_32 = const AssetResource("assets/images/icon_mail_32.png", packageName: null);
  /// asset: assets/images/icon_media_player_32.png
      // ignore: non_constant_identifier_names
      final icon_media_player_32 = const AssetResource("assets/images/icon_media_player_32.png", packageName: null);
  /// asset: assets/images/icon_msn_32.png
      // ignore: non_constant_identifier_names
      final icon_msn_32 = const AssetResource("assets/images/icon_msn_32.png", packageName: null);
  /// asset: assets/images/icon_my_documents_16.png
      // ignore: non_constant_identifier_names
      final icon_my_documents_16 = const AssetResource("assets/images/icon_my_documents_16.png", packageName: null);
  /// asset: assets/images/icon_my_documents_32.png
      // ignore: non_constant_identifier_names
      final icon_my_documents_32 = const AssetResource("assets/images/icon_my_documents_32.png", packageName: null);
  /// asset: assets/images/icon_my_music_32.png
      // ignore: non_constant_identifier_names
      final icon_my_music_32 = const AssetResource("assets/images/icon_my_music_32.png", packageName: null);
  /// asset: assets/images/icon_my_network_16.png
      // ignore: non_constant_identifier_names
      final icon_my_network_16 = const AssetResource("assets/images/icon_my_network_16.png", packageName: null);
  /// asset: assets/images/icon_my_pictures_32.png
      // ignore: non_constant_identifier_names
      final icon_my_pictures_32 = const AssetResource("assets/images/icon_my_pictures_32.png", packageName: null);
  /// asset: assets/images/icon_my_recent_documents_32.png
      // ignore: non_constant_identifier_names
      final icon_my_recent_documents_32 = const AssetResource("assets/images/icon_my_recent_documents_32.png", packageName: null);
  /// asset: assets/images/icon_notepad_16.png
      // ignore: non_constant_identifier_names
      final icon_notepad_16 = const AssetResource("assets/images/icon_notepad_16.png", packageName: null);
  /// asset: assets/images/icon_notepad_32.png
      // ignore: non_constant_identifier_names
      final icon_notepad_32 = const AssetResource("assets/images/icon_notepad_32.png", packageName: null);
  /// asset: assets/images/icon_nso_48.png
      // ignore: non_constant_identifier_names
      final icon_nso_48 = const AssetResource("assets/images/icon_nso_48.png", packageName: null);
  /// asset: assets/images/icon_paint_32.png
      // ignore: non_constant_identifier_names
      final icon_paint_32 = const AssetResource("assets/images/icon_paint_32.png", packageName: null);
  /// asset: assets/images/icon_print_and_fax_32.png
      // ignore: non_constant_identifier_names
      final icon_print_and_fax_32 = const AssetResource("assets/images/icon_print_and_fax_32.png", packageName: null);
  /// asset: assets/images/icon_printer_32.png
      // ignore: non_constant_identifier_names
      final icon_printer_32 = const AssetResource("assets/images/icon_printer_32.png", packageName: null);
  /// asset: assets/images/icon_program_asset_32.png
      // ignore: non_constant_identifier_names
      final icon_program_asset_32 = const AssetResource("assets/images/icon_program_asset_32.png", packageName: null);
  /// asset: assets/images/icon_programs_manager_16.png
      // ignore: non_constant_identifier_names
      final icon_programs_manager_16 = const AssetResource("assets/images/icon_programs_manager_16.png", packageName: null);
  /// asset: assets/images/icon_refresh_32.png
      // ignore: non_constant_identifier_names
      final icon_refresh_32 = const AssetResource("assets/images/icon_refresh_32.png", packageName: null);
  /// asset: assets/images/icon_rogue_horizontal_defense_48.png
      // ignore: non_constant_identifier_names
      final icon_rogue_horizontal_defense_48 = const AssetResource("assets/images/icon_rogue_horizontal_defense_48.png", packageName: null);
  /// asset: assets/images/icon_run_32.png
      // ignore: non_constant_identifier_names
      final icon_run_32 = const AssetResource("assets/images/icon_run_32.png", packageName: null);
  /// asset: assets/images/icon_search_32.png
      // ignore: non_constant_identifier_names
      final icon_search_32 = const AssetResource("assets/images/icon_search_32.png", packageName: null);
  /// asset: assets/images/icon_share_documents_16.png
      // ignore: non_constant_identifier_names
      final icon_share_documents_16 = const AssetResource("assets/images/icon_share_documents_16.png", packageName: null);
  /// asset: assets/images/icon_solitaire_32.png
      // ignore: non_constant_identifier_names
      final icon_solitaire_32 = const AssetResource("assets/images/icon_solitaire_32.png", packageName: null);
  /// asset: assets/images/icon_stop_32.png
      // ignore: non_constant_identifier_names
      final icon_stop_32 = const AssetResource("assets/images/icon_stop_32.png", packageName: null);
  /// asset: assets/images/icon_support_32.png
      // ignore: non_constant_identifier_names
      final icon_support_32 = const AssetResource("assets/images/icon_support_32.png", packageName: null);
  /// asset: assets/images/icon_tetris_puyo_48.png
      // ignore: non_constant_identifier_names
      final icon_tetris_puyo_48 = const AssetResource("assets/images/icon_tetris_puyo_48.png", packageName: null);
  /// asset: assets/images/icon_uno_48.png
      // ignore: non_constant_identifier_names
      final icon_uno_48 = const AssetResource("assets/images/icon_uno_48.png", packageName: null);
  /// asset: assets/images/icon_usb_16.png
      // ignore: non_constant_identifier_names
      final icon_usb_16 = const AssetResource("assets/images/icon_usb_16.png", packageName: null);
  /// asset: assets/images/icon_user_32.png
      // ignore: non_constant_identifier_names
      final icon_user_32 = const AssetResource("assets/images/icon_user_32.png", packageName: null);
  /// asset: assets/images/icon_view_info_16.png
      // ignore: non_constant_identifier_names
      final icon_view_info_16 = const AssetResource("assets/images/icon_view_info_16.png", packageName: null);
  /// asset: assets/images/icon_weiqi_48.png
      // ignore: non_constant_identifier_names
      final icon_weiqi_48 = const AssetResource("assets/images/icon_weiqi_48.png", packageName: null);
  /// asset: assets/images/icon_winamp_32.png
      // ignore: non_constant_identifier_names
      final icon_winamp_32 = const AssetResource("assets/images/icon_winamp_32.png", packageName: null);
  /// asset: assets/images/icon_windows_flag.png
      // ignore: non_constant_identifier_names
      final icon_windows_flag = const AssetResource("assets/images/icon_windows_flag.png", packageName: null);
  /// asset: assets/images/img_windowsXP.png
      // ignore: non_constant_identifier_names
      final img_windowsXP = const AssetResource("assets/images/img_windowsXP.png", packageName: null);
  /// asset: assets/images/minesweeper/checked.png
      // ignore: non_constant_identifier_names
      final checked = const AssetResource("assets/images/minesweeper/checked.png", packageName: null);
  /// asset: assets/images/minesweeper/dead.png
      // ignore: non_constant_identifier_names
      final dead = const AssetResource("assets/images/minesweeper/dead.png", packageName: null);
  /// asset: assets/images/minesweeper/digit-.png
      // ignore: non_constant_identifier_names
      final digit_ = const AssetResource("assets/images/minesweeper/digit-.png", packageName: null);
  /// asset: assets/images/minesweeper/digit0.png
      // ignore: non_constant_identifier_names
      final digit0 = const AssetResource("assets/images/minesweeper/digit0.png", packageName: null);
  /// asset: assets/images/minesweeper/digit1.png
      // ignore: non_constant_identifier_names
      final digit1 = const AssetResource("assets/images/minesweeper/digit1.png", packageName: null);
  /// asset: assets/images/minesweeper/digit2.png
      // ignore: non_constant_identifier_names
      final digit2 = const AssetResource("assets/images/minesweeper/digit2.png", packageName: null);
  /// asset: assets/images/minesweeper/digit3.png
      // ignore: non_constant_identifier_names
      final digit3 = const AssetResource("assets/images/minesweeper/digit3.png", packageName: null);
  /// asset: assets/images/minesweeper/digit4.png
      // ignore: non_constant_identifier_names
      final digit4 = const AssetResource("assets/images/minesweeper/digit4.png", packageName: null);
  /// asset: assets/images/minesweeper/digit5.png
      // ignore: non_constant_identifier_names
      final digit5 = const AssetResource("assets/images/minesweeper/digit5.png", packageName: null);
  /// asset: assets/images/minesweeper/digit6.png
      // ignore: non_constant_identifier_names
      final digit6 = const AssetResource("assets/images/minesweeper/digit6.png", packageName: null);
  /// asset: assets/images/minesweeper/digit7.png
      // ignore: non_constant_identifier_names
      final digit7 = const AssetResource("assets/images/minesweeper/digit7.png", packageName: null);
  /// asset: assets/images/minesweeper/digit8.png
      // ignore: non_constant_identifier_names
      final digit8 = const AssetResource("assets/images/minesweeper/digit8.png", packageName: null);
  /// asset: assets/images/minesweeper/digit9.png
      // ignore: non_constant_identifier_names
      final digit9 = const AssetResource("assets/images/minesweeper/digit9.png", packageName: null);
  /// asset: assets/images/minesweeper/flag.png
      // ignore: non_constant_identifier_names
      final flag = const AssetResource("assets/images/minesweeper/flag.png", packageName: null);
  /// asset: assets/images/minesweeper/icon_mine_32.png
      // ignore: non_constant_identifier_names
      final icon_mine_32 = const AssetResource("assets/images/minesweeper/icon_mine_32.png", packageName: null);
  /// asset: assets/images/minesweeper/mine-ceil.png
      // ignore: non_constant_identifier_names
      final mine_ceil = const AssetResource("assets/images/minesweeper/mine-ceil.png", packageName: null);
  /// asset: assets/images/minesweeper/mine-death.png
      // ignore: non_constant_identifier_names
      final mine_death = const AssetResource("assets/images/minesweeper/mine-death.png", packageName: null);
  /// asset: assets/images/minesweeper/misflagged.png
      // ignore: non_constant_identifier_names
      final misflagged = const AssetResource("assets/images/minesweeper/misflagged.png", packageName: null);
  /// asset: assets/images/minesweeper/ohh.png
      // ignore: non_constant_identifier_names
      final ohh = const AssetResource("assets/images/minesweeper/ohh.png", packageName: null);
  /// asset: assets/images/minesweeper/open1.png
      // ignore: non_constant_identifier_names
      final open1 = const AssetResource("assets/images/minesweeper/open1.png", packageName: null);
  /// asset: assets/images/minesweeper/open2.png
      // ignore: non_constant_identifier_names
      final open2 = const AssetResource("assets/images/minesweeper/open2.png", packageName: null);
  /// asset: assets/images/minesweeper/open3.png
      // ignore: non_constant_identifier_names
      final open3 = const AssetResource("assets/images/minesweeper/open3.png", packageName: null);
  /// asset: assets/images/minesweeper/open4.png
      // ignore: non_constant_identifier_names
      final open4 = const AssetResource("assets/images/minesweeper/open4.png", packageName: null);
  /// asset: assets/images/minesweeper/open5.png
      // ignore: non_constant_identifier_names
      final open5 = const AssetResource("assets/images/minesweeper/open5.png", packageName: null);
  /// asset: assets/images/minesweeper/open6.png
      // ignore: non_constant_identifier_names
      final open6 = const AssetResource("assets/images/minesweeper/open6.png", packageName: null);
  /// asset: assets/images/minesweeper/open7.png
      // ignore: non_constant_identifier_names
      final open7 = const AssetResource("assets/images/minesweeper/open7.png", packageName: null);
  /// asset: assets/images/minesweeper/open8.png
      // ignore: non_constant_identifier_names
      final open8 = const AssetResource("assets/images/minesweeper/open8.png", packageName: null);
  /// asset: assets/images/minesweeper/question.png
      // ignore: non_constant_identifier_names
      final question = const AssetResource("assets/images/minesweeper/question.png", packageName: null);
  /// asset: assets/images/minesweeper/smile.png
      // ignore: non_constant_identifier_names
      final smile = const AssetResource("assets/images/minesweeper/smile.png", packageName: null);
  /// asset: assets/images/minesweeper/win.png
      // ignore: non_constant_identifier_names
      final win = const AssetResource("assets/images/minesweeper/win.png", packageName: null);
  /// asset: assets/images/painter/print_tools_0.png
      // ignore: non_constant_identifier_names
      final print_tools_0 = const AssetResource("assets/images/painter/print_tools_0.png", packageName: null);
  /// asset: assets/images/painter/print_tools_1.png
      // ignore: non_constant_identifier_names
      final print_tools_1 = const AssetResource("assets/images/painter/print_tools_1.png", packageName: null);
  /// asset: assets/images/painter/print_tools_10.png
      // ignore: non_constant_identifier_names
      final print_tools_10 = const AssetResource("assets/images/painter/print_tools_10.png", packageName: null);
  /// asset: assets/images/painter/print_tools_11.png
      // ignore: non_constant_identifier_names
      final print_tools_11 = const AssetResource("assets/images/painter/print_tools_11.png", packageName: null);
  /// asset: assets/images/painter/print_tools_12.png
      // ignore: non_constant_identifier_names
      final print_tools_12 = const AssetResource("assets/images/painter/print_tools_12.png", packageName: null);
  /// asset: assets/images/painter/print_tools_13.png
      // ignore: non_constant_identifier_names
      final print_tools_13 = const AssetResource("assets/images/painter/print_tools_13.png", packageName: null);
  /// asset: assets/images/painter/print_tools_14.png
      // ignore: non_constant_identifier_names
      final print_tools_14 = const AssetResource("assets/images/painter/print_tools_14.png", packageName: null);
  /// asset: assets/images/painter/print_tools_15.png
      // ignore: non_constant_identifier_names
      final print_tools_15 = const AssetResource("assets/images/painter/print_tools_15.png", packageName: null);
  /// asset: assets/images/painter/print_tools_2.png
      // ignore: non_constant_identifier_names
      final print_tools_2 = const AssetResource("assets/images/painter/print_tools_2.png", packageName: null);
  /// asset: assets/images/painter/print_tools_3.png
      // ignore: non_constant_identifier_names
      final print_tools_3 = const AssetResource("assets/images/painter/print_tools_3.png", packageName: null);
  /// asset: assets/images/painter/print_tools_4.png
      // ignore: non_constant_identifier_names
      final print_tools_4 = const AssetResource("assets/images/painter/print_tools_4.png", packageName: null);
  /// asset: assets/images/painter/print_tools_5.png
      // ignore: non_constant_identifier_names
      final print_tools_5 = const AssetResource("assets/images/painter/print_tools_5.png", packageName: null);
  /// asset: assets/images/painter/print_tools_6.png
      // ignore: non_constant_identifier_names
      final print_tools_6 = const AssetResource("assets/images/painter/print_tools_6.png", packageName: null);
  /// asset: assets/images/painter/print_tools_7.png
      // ignore: non_constant_identifier_names
      final print_tools_7 = const AssetResource("assets/images/painter/print_tools_7.png", packageName: null);
  /// asset: assets/images/painter/print_tools_8.png
      // ignore: non_constant_identifier_names
      final print_tools_8 = const AssetResource("assets/images/painter/print_tools_8.png", packageName: null);
  /// asset: assets/images/painter/print_tools_9.png
      // ignore: non_constant_identifier_names
      final print_tools_9 = const AssetResource("assets/images/painter/print_tools_9.png", packageName: null);
  /// asset: assets/images/solitaire/2C.png
      // ignore: non_constant_identifier_names
      final a2C = const AssetResource("assets/images/solitaire/2C.png", packageName: null);
  /// asset: assets/images/solitaire/2D.png
      // ignore: non_constant_identifier_names
      final a2D = const AssetResource("assets/images/solitaire/2D.png", packageName: null);
  /// asset: assets/images/solitaire/2H.png
      // ignore: non_constant_identifier_names
      final a2H = const AssetResource("assets/images/solitaire/2H.png", packageName: null);
  /// asset: assets/images/solitaire/2S.png
      // ignore: non_constant_identifier_names
      final a2S = const AssetResource("assets/images/solitaire/2S.png", packageName: null);
  /// asset: assets/images/solitaire/3C.png
      // ignore: non_constant_identifier_names
      final a3C = const AssetResource("assets/images/solitaire/3C.png", packageName: null);
  /// asset: assets/images/solitaire/3D.png
      // ignore: non_constant_identifier_names
      final a3D = const AssetResource("assets/images/solitaire/3D.png", packageName: null);
  /// asset: assets/images/solitaire/3H.png
      // ignore: non_constant_identifier_names
      final a3H = const AssetResource("assets/images/solitaire/3H.png", packageName: null);
  /// asset: assets/images/solitaire/3S.png
      // ignore: non_constant_identifier_names
      final a3S = const AssetResource("assets/images/solitaire/3S.png", packageName: null);
  /// asset: assets/images/solitaire/4C.png
      // ignore: non_constant_identifier_names
      final a4C = const AssetResource("assets/images/solitaire/4C.png", packageName: null);
  /// asset: assets/images/solitaire/4D.png
      // ignore: non_constant_identifier_names
      final a4D = const AssetResource("assets/images/solitaire/4D.png", packageName: null);
  /// asset: assets/images/solitaire/4H.png
      // ignore: non_constant_identifier_names
      final a4H = const AssetResource("assets/images/solitaire/4H.png", packageName: null);
  /// asset: assets/images/solitaire/4S.png
      // ignore: non_constant_identifier_names
      final a4S = const AssetResource("assets/images/solitaire/4S.png", packageName: null);
  /// asset: assets/images/solitaire/5C.png
      // ignore: non_constant_identifier_names
      final a5C = const AssetResource("assets/images/solitaire/5C.png", packageName: null);
  /// asset: assets/images/solitaire/5D.png
      // ignore: non_constant_identifier_names
      final a5D = const AssetResource("assets/images/solitaire/5D.png", packageName: null);
  /// asset: assets/images/solitaire/5H.png
      // ignore: non_constant_identifier_names
      final a5H = const AssetResource("assets/images/solitaire/5H.png", packageName: null);
  /// asset: assets/images/solitaire/5S.png
      // ignore: non_constant_identifier_names
      final a5S = const AssetResource("assets/images/solitaire/5S.png", packageName: null);
  /// asset: assets/images/solitaire/6C.png
      // ignore: non_constant_identifier_names
      final a6C = const AssetResource("assets/images/solitaire/6C.png", packageName: null);
  /// asset: assets/images/solitaire/6D.png
      // ignore: non_constant_identifier_names
      final a6D = const AssetResource("assets/images/solitaire/6D.png", packageName: null);
  /// asset: assets/images/solitaire/6H.png
      // ignore: non_constant_identifier_names
      final a6H = const AssetResource("assets/images/solitaire/6H.png", packageName: null);
  /// asset: assets/images/solitaire/6S.png
      // ignore: non_constant_identifier_names
      final a6S = const AssetResource("assets/images/solitaire/6S.png", packageName: null);
  /// asset: assets/images/solitaire/7C.png
      // ignore: non_constant_identifier_names
      final a7C = const AssetResource("assets/images/solitaire/7C.png", packageName: null);
  /// asset: assets/images/solitaire/7D.png
      // ignore: non_constant_identifier_names
      final a7D = const AssetResource("assets/images/solitaire/7D.png", packageName: null);
  /// asset: assets/images/solitaire/7H.png
      // ignore: non_constant_identifier_names
      final a7H = const AssetResource("assets/images/solitaire/7H.png", packageName: null);
  /// asset: assets/images/solitaire/7S.png
      // ignore: non_constant_identifier_names
      final a7S = const AssetResource("assets/images/solitaire/7S.png", packageName: null);
  /// asset: assets/images/solitaire/8C.png
      // ignore: non_constant_identifier_names
      final a8C = const AssetResource("assets/images/solitaire/8C.png", packageName: null);
  /// asset: assets/images/solitaire/8D.png
      // ignore: non_constant_identifier_names
      final a8D = const AssetResource("assets/images/solitaire/8D.png", packageName: null);
  /// asset: assets/images/solitaire/8H.png
      // ignore: non_constant_identifier_names
      final a8H = const AssetResource("assets/images/solitaire/8H.png", packageName: null);
  /// asset: assets/images/solitaire/8S.png
      // ignore: non_constant_identifier_names
      final a8S = const AssetResource("assets/images/solitaire/8S.png", packageName: null);
  /// asset: assets/images/solitaire/9C.png
      // ignore: non_constant_identifier_names
      final a9C = const AssetResource("assets/images/solitaire/9C.png", packageName: null);
  /// asset: assets/images/solitaire/9D.png
      // ignore: non_constant_identifier_names
      final a9D = const AssetResource("assets/images/solitaire/9D.png", packageName: null);
  /// asset: assets/images/solitaire/9H.png
      // ignore: non_constant_identifier_names
      final a9H = const AssetResource("assets/images/solitaire/9H.png", packageName: null);
  /// asset: assets/images/solitaire/9S.png
      // ignore: non_constant_identifier_names
      final a9S = const AssetResource("assets/images/solitaire/9S.png", packageName: null);
  /// asset: assets/images/solitaire/AC.png
      // ignore: non_constant_identifier_names
      final aC = const AssetResource("assets/images/solitaire/AC.png", packageName: null);
  /// asset: assets/images/solitaire/AD.png
      // ignore: non_constant_identifier_names
      final aD = const AssetResource("assets/images/solitaire/AD.png", packageName: null);
  /// asset: assets/images/solitaire/AH.png
      // ignore: non_constant_identifier_names
      final aH = const AssetResource("assets/images/solitaire/AH.png", packageName: null);
  /// asset: assets/images/solitaire/AS.png
      // ignore: non_constant_identifier_names
      final aS = const AssetResource("assets/images/solitaire/AS.png", packageName: null);
  /// asset: assets/images/solitaire/JC.png
      // ignore: non_constant_identifier_names
      final jC = const AssetResource("assets/images/solitaire/JC.png", packageName: null);
  /// asset: assets/images/solitaire/JD.png
      // ignore: non_constant_identifier_names
      final jD = const AssetResource("assets/images/solitaire/JD.png", packageName: null);
  /// asset: assets/images/solitaire/JH.png
      // ignore: non_constant_identifier_names
      final jH = const AssetResource("assets/images/solitaire/JH.png", packageName: null);
  /// asset: assets/images/solitaire/JS.png
      // ignore: non_constant_identifier_names
      final jS = const AssetResource("assets/images/solitaire/JS.png", packageName: null);
  /// asset: assets/images/solitaire/KC.png
      // ignore: non_constant_identifier_names
      final kC = const AssetResource("assets/images/solitaire/KC.png", packageName: null);
  /// asset: assets/images/solitaire/KD.png
      // ignore: non_constant_identifier_names
      final kD = const AssetResource("assets/images/solitaire/KD.png", packageName: null);
  /// asset: assets/images/solitaire/KH.png
      // ignore: non_constant_identifier_names
      final kH = const AssetResource("assets/images/solitaire/KH.png", packageName: null);
  /// asset: assets/images/solitaire/KS.png
      // ignore: non_constant_identifier_names
      final kS = const AssetResource("assets/images/solitaire/KS.png", packageName: null);
  /// asset: assets/images/solitaire/QC.png
      // ignore: non_constant_identifier_names
      final qC = const AssetResource("assets/images/solitaire/QC.png", packageName: null);
  /// asset: assets/images/solitaire/QD.png
      // ignore: non_constant_identifier_names
      final qD = const AssetResource("assets/images/solitaire/QD.png", packageName: null);
  /// asset: assets/images/solitaire/QH.png
      // ignore: non_constant_identifier_names
      final qH = const AssetResource("assets/images/solitaire/QH.png", packageName: null);
  /// asset: assets/images/solitaire/QS.png
      // ignore: non_constant_identifier_names
      final qS = const AssetResource("assets/images/solitaire/QS.png", packageName: null);
  /// asset: assets/images/solitaire/TC.png
      // ignore: non_constant_identifier_names
      final tC = const AssetResource("assets/images/solitaire/TC.png", packageName: null);
  /// asset: assets/images/solitaire/TD.png
      // ignore: non_constant_identifier_names
      final tD = const AssetResource("assets/images/solitaire/TD.png", packageName: null);
  /// asset: assets/images/solitaire/TH.png
      // ignore: non_constant_identifier_names
      final tH = const AssetResource("assets/images/solitaire/TH.png", packageName: null);
  /// asset: assets/images/solitaire/TS.png
      // ignore: non_constant_identifier_names
      final tS = const AssetResource("assets/images/solitaire/TS.png", packageName: null);
  /// asset: assets/images/solitaire/joker.png
      // ignore: non_constant_identifier_names
      final joker = const AssetResource("assets/images/solitaire/joker.png", packageName: null);
  /// asset: assets/images/transparent_background.jpg
      // ignore: non_constant_identifier_names
      final transparent_background_jpg = const AssetResource("assets/images/transparent_background.jpg", packageName: null);
      }
// ignore: camel_case_types
    class _R_Svg_AssetResource {
      const _R_Svg_AssetResource();
    
    }
// ignore: camel_case_types
    class _R_Text_AssetResource {
      const _R_Text_AssetResource();
    
    }
/// This `_R_Image` class is generated and contains references to static non-svg type image asset resources.
    // ignore: camel_case_types
    class _R_Image {
      const _R_Image();
    
      final asset = const _R_Image_AssetResource();
    
  /// asset: assets/images/btn_back.png
      // ignore: non_constant_identifier_names
      AssetImage btn_back() {
        return AssetImage(asset.btn_back.keyName);
      }
  /// asset: assets/images/btn_forward.png
      // ignore: non_constant_identifier_names
      AssetImage btn_forward() {
        return AssetImage(asset.btn_forward.keyName);
      }
  /// asset: assets/images/btn_start.png
      // ignore: non_constant_identifier_names
      AssetImage btn_start() {
        return AssetImage(asset.btn_start.keyName);
      }
  /// asset: assets/images/icon_alian_48.png
      // ignore: non_constant_identifier_names
      AssetImage icon_alian_48() {
        return AssetImage(asset.icon_alian_48.keyName);
      }
  /// asset: assets/images/icon_audio_16.png
      // ignore: non_constant_identifier_names
      AssetImage icon_audio_16() {
        return AssetImage(asset.icon_audio_16.keyName);
      }
  /// asset: assets/images/icon_cd_48.png
      // ignore: non_constant_identifier_names
      AssetImage icon_cd_48() {
        return AssetImage(asset.icon_cd_48.keyName);
      }
  /// asset: assets/images/icon_checklist_32.png
      // ignore: non_constant_identifier_names
      AssetImage icon_checklist_32() {
        return AssetImage(asset.icon_checklist_32.keyName);
      }
  /// asset: assets/images/icon_computer_16.png
      // ignore: non_constant_identifier_names
      AssetImage icon_computer_16() {
        return AssetImage(asset.icon_computer_16.keyName);
      }
  /// asset: assets/images/icon_computer_32.png
      // ignore: non_constant_identifier_names
      AssetImage icon_computer_32() {
        return AssetImage(asset.icon_computer_32.keyName);
      }
  /// asset: assets/images/icon_connect_to_32.png
      // ignore: non_constant_identifier_names
      AssetImage icon_connect_to_32() {
        return AssetImage(asset.icon_connect_to_32.keyName);
      }
  /// asset: assets/images/icon_control_panel_16.png
      // ignore: non_constant_identifier_names
      AssetImage icon_control_panel_16() {
        return AssetImage(asset.icon_control_panel_16.keyName);
      }
  /// asset: assets/images/icon_control_panel_32.png
      // ignore: non_constant_identifier_names
      AssetImage icon_control_panel_32() {
        return AssetImage(asset.icon_control_panel_32.keyName);
      }
  /// asset: assets/images/icon_dangerous_16.png
      // ignore: non_constant_identifier_names
      AssetImage icon_dangerous_16() {
        return AssetImage(asset.icon_dangerous_16.keyName);
      }
  /// asset: assets/images/icon_disk_48.png
      // ignore: non_constant_identifier_names
      AssetImage icon_disk_48() {
        return AssetImage(asset.icon_disk_48.keyName);
      }
  /// asset: assets/images/icon_document_32.png
      // ignore: non_constant_identifier_names
      AssetImage icon_document_32() {
        return AssetImage(asset.icon_document_32.keyName);
      }
  /// asset: assets/images/icon_dropdown_16.png
      // ignore: non_constant_identifier_names
      AssetImage icon_dropdown_16() {
        return AssetImage(asset.icon_dropdown_16.keyName);
      }
  /// asset: assets/images/icon_email_32.png
      // ignore: non_constant_identifier_names
      AssetImage icon_email_32() {
        return AssetImage(asset.icon_email_32.keyName);
      }
  /// asset: assets/images/icon_favorites_32.png
      // ignore: non_constant_identifier_names
      AssetImage icon_favorites_32() {
        return AssetImage(asset.icon_favorites_32.keyName);
      }
  /// asset: assets/images/icon_folder_32.png
      // ignore: non_constant_identifier_names
      AssetImage icon_folder_32() {
        return AssetImage(asset.icon_folder_32.keyName);
      }
  /// asset: assets/images/icon_folder_48.png
      // ignore: non_constant_identifier_names
      AssetImage icon_folder_48() {
        return AssetImage(asset.icon_folder_48.keyName);
      }
  /// asset: assets/images/icon_folder_up.png
      // ignore: non_constant_identifier_names
      AssetImage icon_folder_up() {
        return AssetImage(asset.icon_folder_up.keyName);
      }
  /// asset: assets/images/icon_fortune_wheel_48.png
      // ignore: non_constant_identifier_names
      AssetImage icon_fortune_wheel_48() {
        return AssetImage(asset.icon_fortune_wheel_48.keyName);
      }
  /// asset: assets/images/icon_hexagon_defense_48.png
      // ignore: non_constant_identifier_names
      AssetImage icon_hexagon_defense_48() {
        return AssetImage(asset.icon_hexagon_defense_48.keyName);
      }
  /// asset: assets/images/icon_hexagon_jubeat_48.png
      // ignore: non_constant_identifier_names
      AssetImage icon_hexagon_jubeat_48() {
        return AssetImage(asset.icon_hexagon_jubeat_48.keyName);
      }
  /// asset: assets/images/icon_hexagon_tos_48.png
      // ignore: non_constant_identifier_names
      AssetImage icon_hexagon_tos_48() {
        return AssetImage(asset.icon_hexagon_tos_48.keyName);
      }
  /// asset: assets/images/icon_history_32.png
      // ignore: non_constant_identifier_names
      AssetImage icon_history_32() {
        return AssetImage(asset.icon_history_32.keyName);
      }
  /// asset: assets/images/icon_home_32.png
      // ignore: non_constant_identifier_names
      AssetImage icon_home_32() {
        return AssetImage(asset.icon_home_32.keyName);
      }
  /// asset: assets/images/icon_ie_paper_16.png
      // ignore: non_constant_identifier_names
      AssetImage icon_ie_paper_16() {
        return AssetImage(asset.icon_ie_paper_16.keyName);
      }
  /// asset: assets/images/icon_internet_32.png
      // ignore: non_constant_identifier_names
      AssetImage icon_internet_32() {
        return AssetImage(asset.icon_internet_32.keyName);
      }
  /// asset: assets/images/icon_l_game_48.png
      // ignore: non_constant_identifier_names
      AssetImage icon_l_game_48() {
        return AssetImage(asset.icon_l_game_48.keyName);
      }
  /// asset: assets/images/icon_listen_music_learn_language_48.png
      // ignore: non_constant_identifier_names
      AssetImage icon_listen_music_learn_language_48() {
        return AssetImage(asset.icon_listen_music_learn_language_48.keyName);
      }
  /// asset: assets/images/icon_mail_32.png
      // ignore: non_constant_identifier_names
      AssetImage icon_mail_32() {
        return AssetImage(asset.icon_mail_32.keyName);
      }
  /// asset: assets/images/icon_media_player_32.png
      // ignore: non_constant_identifier_names
      AssetImage icon_media_player_32() {
        return AssetImage(asset.icon_media_player_32.keyName);
      }
  /// asset: assets/images/icon_msn_32.png
      // ignore: non_constant_identifier_names
      AssetImage icon_msn_32() {
        return AssetImage(asset.icon_msn_32.keyName);
      }
  /// asset: assets/images/icon_my_documents_16.png
      // ignore: non_constant_identifier_names
      AssetImage icon_my_documents_16() {
        return AssetImage(asset.icon_my_documents_16.keyName);
      }
  /// asset: assets/images/icon_my_documents_32.png
      // ignore: non_constant_identifier_names
      AssetImage icon_my_documents_32() {
        return AssetImage(asset.icon_my_documents_32.keyName);
      }
  /// asset: assets/images/icon_my_music_32.png
      // ignore: non_constant_identifier_names
      AssetImage icon_my_music_32() {
        return AssetImage(asset.icon_my_music_32.keyName);
      }
  /// asset: assets/images/icon_my_network_16.png
      // ignore: non_constant_identifier_names
      AssetImage icon_my_network_16() {
        return AssetImage(asset.icon_my_network_16.keyName);
      }
  /// asset: assets/images/icon_my_pictures_32.png
      // ignore: non_constant_identifier_names
      AssetImage icon_my_pictures_32() {
        return AssetImage(asset.icon_my_pictures_32.keyName);
      }
  /// asset: assets/images/icon_my_recent_documents_32.png
      // ignore: non_constant_identifier_names
      AssetImage icon_my_recent_documents_32() {
        return AssetImage(asset.icon_my_recent_documents_32.keyName);
      }
  /// asset: assets/images/icon_notepad_16.png
      // ignore: non_constant_identifier_names
      AssetImage icon_notepad_16() {
        return AssetImage(asset.icon_notepad_16.keyName);
      }
  /// asset: assets/images/icon_notepad_32.png
      // ignore: non_constant_identifier_names
      AssetImage icon_notepad_32() {
        return AssetImage(asset.icon_notepad_32.keyName);
      }
  /// asset: assets/images/icon_nso_48.png
      // ignore: non_constant_identifier_names
      AssetImage icon_nso_48() {
        return AssetImage(asset.icon_nso_48.keyName);
      }
  /// asset: assets/images/icon_paint_32.png
      // ignore: non_constant_identifier_names
      AssetImage icon_paint_32() {
        return AssetImage(asset.icon_paint_32.keyName);
      }
  /// asset: assets/images/icon_print_and_fax_32.png
      // ignore: non_constant_identifier_names
      AssetImage icon_print_and_fax_32() {
        return AssetImage(asset.icon_print_and_fax_32.keyName);
      }
  /// asset: assets/images/icon_printer_32.png
      // ignore: non_constant_identifier_names
      AssetImage icon_printer_32() {
        return AssetImage(asset.icon_printer_32.keyName);
      }
  /// asset: assets/images/icon_program_asset_32.png
      // ignore: non_constant_identifier_names
      AssetImage icon_program_asset_32() {
        return AssetImage(asset.icon_program_asset_32.keyName);
      }
  /// asset: assets/images/icon_programs_manager_16.png
      // ignore: non_constant_identifier_names
      AssetImage icon_programs_manager_16() {
        return AssetImage(asset.icon_programs_manager_16.keyName);
      }
  /// asset: assets/images/icon_refresh_32.png
      // ignore: non_constant_identifier_names
      AssetImage icon_refresh_32() {
        return AssetImage(asset.icon_refresh_32.keyName);
      }
  /// asset: assets/images/icon_rogue_horizontal_defense_48.png
      // ignore: non_constant_identifier_names
      AssetImage icon_rogue_horizontal_defense_48() {
        return AssetImage(asset.icon_rogue_horizontal_defense_48.keyName);
      }
  /// asset: assets/images/icon_run_32.png
      // ignore: non_constant_identifier_names
      AssetImage icon_run_32() {
        return AssetImage(asset.icon_run_32.keyName);
      }
  /// asset: assets/images/icon_search_32.png
      // ignore: non_constant_identifier_names
      AssetImage icon_search_32() {
        return AssetImage(asset.icon_search_32.keyName);
      }
  /// asset: assets/images/icon_share_documents_16.png
      // ignore: non_constant_identifier_names
      AssetImage icon_share_documents_16() {
        return AssetImage(asset.icon_share_documents_16.keyName);
      }
  /// asset: assets/images/icon_solitaire_32.png
      // ignore: non_constant_identifier_names
      AssetImage icon_solitaire_32() {
        return AssetImage(asset.icon_solitaire_32.keyName);
      }
  /// asset: assets/images/icon_stop_32.png
      // ignore: non_constant_identifier_names
      AssetImage icon_stop_32() {
        return AssetImage(asset.icon_stop_32.keyName);
      }
  /// asset: assets/images/icon_support_32.png
      // ignore: non_constant_identifier_names
      AssetImage icon_support_32() {
        return AssetImage(asset.icon_support_32.keyName);
      }
  /// asset: assets/images/icon_tetris_puyo_48.png
      // ignore: non_constant_identifier_names
      AssetImage icon_tetris_puyo_48() {
        return AssetImage(asset.icon_tetris_puyo_48.keyName);
      }
  /// asset: assets/images/icon_uno_48.png
      // ignore: non_constant_identifier_names
      AssetImage icon_uno_48() {
        return AssetImage(asset.icon_uno_48.keyName);
      }
  /// asset: assets/images/icon_usb_16.png
      // ignore: non_constant_identifier_names
      AssetImage icon_usb_16() {
        return AssetImage(asset.icon_usb_16.keyName);
      }
  /// asset: assets/images/icon_user_32.png
      // ignore: non_constant_identifier_names
      AssetImage icon_user_32() {
        return AssetImage(asset.icon_user_32.keyName);
      }
  /// asset: assets/images/icon_view_info_16.png
      // ignore: non_constant_identifier_names
      AssetImage icon_view_info_16() {
        return AssetImage(asset.icon_view_info_16.keyName);
      }
  /// asset: assets/images/icon_weiqi_48.png
      // ignore: non_constant_identifier_names
      AssetImage icon_weiqi_48() {
        return AssetImage(asset.icon_weiqi_48.keyName);
      }
  /// asset: assets/images/icon_winamp_32.png
      // ignore: non_constant_identifier_names
      AssetImage icon_winamp_32() {
        return AssetImage(asset.icon_winamp_32.keyName);
      }
  /// asset: assets/images/icon_windows_flag.png
      // ignore: non_constant_identifier_names
      AssetImage icon_windows_flag() {
        return AssetImage(asset.icon_windows_flag.keyName);
      }
  /// asset: assets/images/img_windowsXP.png
      // ignore: non_constant_identifier_names
      AssetImage img_windowsXP() {
        return AssetImage(asset.img_windowsXP.keyName);
      }
  /// asset: assets/images/minesweeper/checked.png
      // ignore: non_constant_identifier_names
      AssetImage checked() {
        return AssetImage(asset.checked.keyName);
      }
  /// asset: assets/images/minesweeper/dead.png
      // ignore: non_constant_identifier_names
      AssetImage dead() {
        return AssetImage(asset.dead.keyName);
      }
  /// asset: assets/images/minesweeper/digit-.png
      // ignore: non_constant_identifier_names
      AssetImage digit_() {
        return AssetImage(asset.digit_.keyName);
      }
  /// asset: assets/images/minesweeper/digit0.png
      // ignore: non_constant_identifier_names
      AssetImage digit0() {
        return AssetImage(asset.digit0.keyName);
      }
  /// asset: assets/images/minesweeper/digit1.png
      // ignore: non_constant_identifier_names
      AssetImage digit1() {
        return AssetImage(asset.digit1.keyName);
      }
  /// asset: assets/images/minesweeper/digit2.png
      // ignore: non_constant_identifier_names
      AssetImage digit2() {
        return AssetImage(asset.digit2.keyName);
      }
  /// asset: assets/images/minesweeper/digit3.png
      // ignore: non_constant_identifier_names
      AssetImage digit3() {
        return AssetImage(asset.digit3.keyName);
      }
  /// asset: assets/images/minesweeper/digit4.png
      // ignore: non_constant_identifier_names
      AssetImage digit4() {
        return AssetImage(asset.digit4.keyName);
      }
  /// asset: assets/images/minesweeper/digit5.png
      // ignore: non_constant_identifier_names
      AssetImage digit5() {
        return AssetImage(asset.digit5.keyName);
      }
  /// asset: assets/images/minesweeper/digit6.png
      // ignore: non_constant_identifier_names
      AssetImage digit6() {
        return AssetImage(asset.digit6.keyName);
      }
  /// asset: assets/images/minesweeper/digit7.png
      // ignore: non_constant_identifier_names
      AssetImage digit7() {
        return AssetImage(asset.digit7.keyName);
      }
  /// asset: assets/images/minesweeper/digit8.png
      // ignore: non_constant_identifier_names
      AssetImage digit8() {
        return AssetImage(asset.digit8.keyName);
      }
  /// asset: assets/images/minesweeper/digit9.png
      // ignore: non_constant_identifier_names
      AssetImage digit9() {
        return AssetImage(asset.digit9.keyName);
      }
  /// asset: assets/images/minesweeper/flag.png
      // ignore: non_constant_identifier_names
      AssetImage flag() {
        return AssetImage(asset.flag.keyName);
      }
  /// asset: assets/images/minesweeper/icon_mine_32.png
      // ignore: non_constant_identifier_names
      AssetImage icon_mine_32() {
        return AssetImage(asset.icon_mine_32.keyName);
      }
  /// asset: assets/images/minesweeper/mine-ceil.png
      // ignore: non_constant_identifier_names
      AssetImage mine_ceil() {
        return AssetImage(asset.mine_ceil.keyName);
      }
  /// asset: assets/images/minesweeper/mine-death.png
      // ignore: non_constant_identifier_names
      AssetImage mine_death() {
        return AssetImage(asset.mine_death.keyName);
      }
  /// asset: assets/images/minesweeper/misflagged.png
      // ignore: non_constant_identifier_names
      AssetImage misflagged() {
        return AssetImage(asset.misflagged.keyName);
      }
  /// asset: assets/images/minesweeper/ohh.png
      // ignore: non_constant_identifier_names
      AssetImage ohh() {
        return AssetImage(asset.ohh.keyName);
      }
  /// asset: assets/images/minesweeper/open1.png
      // ignore: non_constant_identifier_names
      AssetImage open1() {
        return AssetImage(asset.open1.keyName);
      }
  /// asset: assets/images/minesweeper/open2.png
      // ignore: non_constant_identifier_names
      AssetImage open2() {
        return AssetImage(asset.open2.keyName);
      }
  /// asset: assets/images/minesweeper/open3.png
      // ignore: non_constant_identifier_names
      AssetImage open3() {
        return AssetImage(asset.open3.keyName);
      }
  /// asset: assets/images/minesweeper/open4.png
      // ignore: non_constant_identifier_names
      AssetImage open4() {
        return AssetImage(asset.open4.keyName);
      }
  /// asset: assets/images/minesweeper/open5.png
      // ignore: non_constant_identifier_names
      AssetImage open5() {
        return AssetImage(asset.open5.keyName);
      }
  /// asset: assets/images/minesweeper/open6.png
      // ignore: non_constant_identifier_names
      AssetImage open6() {
        return AssetImage(asset.open6.keyName);
      }
  /// asset: assets/images/minesweeper/open7.png
      // ignore: non_constant_identifier_names
      AssetImage open7() {
        return AssetImage(asset.open7.keyName);
      }
  /// asset: assets/images/minesweeper/open8.png
      // ignore: non_constant_identifier_names
      AssetImage open8() {
        return AssetImage(asset.open8.keyName);
      }
  /// asset: assets/images/minesweeper/question.png
      // ignore: non_constant_identifier_names
      AssetImage question() {
        return AssetImage(asset.question.keyName);
      }
  /// asset: assets/images/minesweeper/smile.png
      // ignore: non_constant_identifier_names
      AssetImage smile() {
        return AssetImage(asset.smile.keyName);
      }
  /// asset: assets/images/minesweeper/win.png
      // ignore: non_constant_identifier_names
      AssetImage win() {
        return AssetImage(asset.win.keyName);
      }
  /// asset: assets/images/painter/print_tools_0.png
      // ignore: non_constant_identifier_names
      AssetImage print_tools_0() {
        return AssetImage(asset.print_tools_0.keyName);
      }
  /// asset: assets/images/painter/print_tools_1.png
      // ignore: non_constant_identifier_names
      AssetImage print_tools_1() {
        return AssetImage(asset.print_tools_1.keyName);
      }
  /// asset: assets/images/painter/print_tools_10.png
      // ignore: non_constant_identifier_names
      AssetImage print_tools_10() {
        return AssetImage(asset.print_tools_10.keyName);
      }
  /// asset: assets/images/painter/print_tools_11.png
      // ignore: non_constant_identifier_names
      AssetImage print_tools_11() {
        return AssetImage(asset.print_tools_11.keyName);
      }
  /// asset: assets/images/painter/print_tools_12.png
      // ignore: non_constant_identifier_names
      AssetImage print_tools_12() {
        return AssetImage(asset.print_tools_12.keyName);
      }
  /// asset: assets/images/painter/print_tools_13.png
      // ignore: non_constant_identifier_names
      AssetImage print_tools_13() {
        return AssetImage(asset.print_tools_13.keyName);
      }
  /// asset: assets/images/painter/print_tools_14.png
      // ignore: non_constant_identifier_names
      AssetImage print_tools_14() {
        return AssetImage(asset.print_tools_14.keyName);
      }
  /// asset: assets/images/painter/print_tools_15.png
      // ignore: non_constant_identifier_names
      AssetImage print_tools_15() {
        return AssetImage(asset.print_tools_15.keyName);
      }
  /// asset: assets/images/painter/print_tools_2.png
      // ignore: non_constant_identifier_names
      AssetImage print_tools_2() {
        return AssetImage(asset.print_tools_2.keyName);
      }
  /// asset: assets/images/painter/print_tools_3.png
      // ignore: non_constant_identifier_names
      AssetImage print_tools_3() {
        return AssetImage(asset.print_tools_3.keyName);
      }
  /// asset: assets/images/painter/print_tools_4.png
      // ignore: non_constant_identifier_names
      AssetImage print_tools_4() {
        return AssetImage(asset.print_tools_4.keyName);
      }
  /// asset: assets/images/painter/print_tools_5.png
      // ignore: non_constant_identifier_names
      AssetImage print_tools_5() {
        return AssetImage(asset.print_tools_5.keyName);
      }
  /// asset: assets/images/painter/print_tools_6.png
      // ignore: non_constant_identifier_names
      AssetImage print_tools_6() {
        return AssetImage(asset.print_tools_6.keyName);
      }
  /// asset: assets/images/painter/print_tools_7.png
      // ignore: non_constant_identifier_names
      AssetImage print_tools_7() {
        return AssetImage(asset.print_tools_7.keyName);
      }
  /// asset: assets/images/painter/print_tools_8.png
      // ignore: non_constant_identifier_names
      AssetImage print_tools_8() {
        return AssetImage(asset.print_tools_8.keyName);
      }
  /// asset: assets/images/painter/print_tools_9.png
      // ignore: non_constant_identifier_names
      AssetImage print_tools_9() {
        return AssetImage(asset.print_tools_9.keyName);
      }
  /// asset: assets/images/solitaire/2C.png
      // ignore: non_constant_identifier_names
      AssetImage a2C() {
        return AssetImage(asset.a2C.keyName);
      }
  /// asset: assets/images/solitaire/2D.png
      // ignore: non_constant_identifier_names
      AssetImage a2D() {
        return AssetImage(asset.a2D.keyName);
      }
  /// asset: assets/images/solitaire/2H.png
      // ignore: non_constant_identifier_names
      AssetImage a2H() {
        return AssetImage(asset.a2H.keyName);
      }
  /// asset: assets/images/solitaire/2S.png
      // ignore: non_constant_identifier_names
      AssetImage a2S() {
        return AssetImage(asset.a2S.keyName);
      }
  /// asset: assets/images/solitaire/3C.png
      // ignore: non_constant_identifier_names
      AssetImage a3C() {
        return AssetImage(asset.a3C.keyName);
      }
  /// asset: assets/images/solitaire/3D.png
      // ignore: non_constant_identifier_names
      AssetImage a3D() {
        return AssetImage(asset.a3D.keyName);
      }
  /// asset: assets/images/solitaire/3H.png
      // ignore: non_constant_identifier_names
      AssetImage a3H() {
        return AssetImage(asset.a3H.keyName);
      }
  /// asset: assets/images/solitaire/3S.png
      // ignore: non_constant_identifier_names
      AssetImage a3S() {
        return AssetImage(asset.a3S.keyName);
      }
  /// asset: assets/images/solitaire/4C.png
      // ignore: non_constant_identifier_names
      AssetImage a4C() {
        return AssetImage(asset.a4C.keyName);
      }
  /// asset: assets/images/solitaire/4D.png
      // ignore: non_constant_identifier_names
      AssetImage a4D() {
        return AssetImage(asset.a4D.keyName);
      }
  /// asset: assets/images/solitaire/4H.png
      // ignore: non_constant_identifier_names
      AssetImage a4H() {
        return AssetImage(asset.a4H.keyName);
      }
  /// asset: assets/images/solitaire/4S.png
      // ignore: non_constant_identifier_names
      AssetImage a4S() {
        return AssetImage(asset.a4S.keyName);
      }
  /// asset: assets/images/solitaire/5C.png
      // ignore: non_constant_identifier_names
      AssetImage a5C() {
        return AssetImage(asset.a5C.keyName);
      }
  /// asset: assets/images/solitaire/5D.png
      // ignore: non_constant_identifier_names
      AssetImage a5D() {
        return AssetImage(asset.a5D.keyName);
      }
  /// asset: assets/images/solitaire/5H.png
      // ignore: non_constant_identifier_names
      AssetImage a5H() {
        return AssetImage(asset.a5H.keyName);
      }
  /// asset: assets/images/solitaire/5S.png
      // ignore: non_constant_identifier_names
      AssetImage a5S() {
        return AssetImage(asset.a5S.keyName);
      }
  /// asset: assets/images/solitaire/6C.png
      // ignore: non_constant_identifier_names
      AssetImage a6C() {
        return AssetImage(asset.a6C.keyName);
      }
  /// asset: assets/images/solitaire/6D.png
      // ignore: non_constant_identifier_names
      AssetImage a6D() {
        return AssetImage(asset.a6D.keyName);
      }
  /// asset: assets/images/solitaire/6H.png
      // ignore: non_constant_identifier_names
      AssetImage a6H() {
        return AssetImage(asset.a6H.keyName);
      }
  /// asset: assets/images/solitaire/6S.png
      // ignore: non_constant_identifier_names
      AssetImage a6S() {
        return AssetImage(asset.a6S.keyName);
      }
  /// asset: assets/images/solitaire/7C.png
      // ignore: non_constant_identifier_names
      AssetImage a7C() {
        return AssetImage(asset.a7C.keyName);
      }
  /// asset: assets/images/solitaire/7D.png
      // ignore: non_constant_identifier_names
      AssetImage a7D() {
        return AssetImage(asset.a7D.keyName);
      }
  /// asset: assets/images/solitaire/7H.png
      // ignore: non_constant_identifier_names
      AssetImage a7H() {
        return AssetImage(asset.a7H.keyName);
      }
  /// asset: assets/images/solitaire/7S.png
      // ignore: non_constant_identifier_names
      AssetImage a7S() {
        return AssetImage(asset.a7S.keyName);
      }
  /// asset: assets/images/solitaire/8C.png
      // ignore: non_constant_identifier_names
      AssetImage a8C() {
        return AssetImage(asset.a8C.keyName);
      }
  /// asset: assets/images/solitaire/8D.png
      // ignore: non_constant_identifier_names
      AssetImage a8D() {
        return AssetImage(asset.a8D.keyName);
      }
  /// asset: assets/images/solitaire/8H.png
      // ignore: non_constant_identifier_names
      AssetImage a8H() {
        return AssetImage(asset.a8H.keyName);
      }
  /// asset: assets/images/solitaire/8S.png
      // ignore: non_constant_identifier_names
      AssetImage a8S() {
        return AssetImage(asset.a8S.keyName);
      }
  /// asset: assets/images/solitaire/9C.png
      // ignore: non_constant_identifier_names
      AssetImage a9C() {
        return AssetImage(asset.a9C.keyName);
      }
  /// asset: assets/images/solitaire/9D.png
      // ignore: non_constant_identifier_names
      AssetImage a9D() {
        return AssetImage(asset.a9D.keyName);
      }
  /// asset: assets/images/solitaire/9H.png
      // ignore: non_constant_identifier_names
      AssetImage a9H() {
        return AssetImage(asset.a9H.keyName);
      }
  /// asset: assets/images/solitaire/9S.png
      // ignore: non_constant_identifier_names
      AssetImage a9S() {
        return AssetImage(asset.a9S.keyName);
      }
  /// asset: assets/images/solitaire/AC.png
      // ignore: non_constant_identifier_names
      AssetImage aC() {
        return AssetImage(asset.aC.keyName);
      }
  /// asset: assets/images/solitaire/AD.png
      // ignore: non_constant_identifier_names
      AssetImage aD() {
        return AssetImage(asset.aD.keyName);
      }
  /// asset: assets/images/solitaire/AH.png
      // ignore: non_constant_identifier_names
      AssetImage aH() {
        return AssetImage(asset.aH.keyName);
      }
  /// asset: assets/images/solitaire/AS.png
      // ignore: non_constant_identifier_names
      AssetImage aS() {
        return AssetImage(asset.aS.keyName);
      }
  /// asset: assets/images/solitaire/JC.png
      // ignore: non_constant_identifier_names
      AssetImage jC() {
        return AssetImage(asset.jC.keyName);
      }
  /// asset: assets/images/solitaire/JD.png
      // ignore: non_constant_identifier_names
      AssetImage jD() {
        return AssetImage(asset.jD.keyName);
      }
  /// asset: assets/images/solitaire/JH.png
      // ignore: non_constant_identifier_names
      AssetImage jH() {
        return AssetImage(asset.jH.keyName);
      }
  /// asset: assets/images/solitaire/JS.png
      // ignore: non_constant_identifier_names
      AssetImage jS() {
        return AssetImage(asset.jS.keyName);
      }
  /// asset: assets/images/solitaire/KC.png
      // ignore: non_constant_identifier_names
      AssetImage kC() {
        return AssetImage(asset.kC.keyName);
      }
  /// asset: assets/images/solitaire/KD.png
      // ignore: non_constant_identifier_names
      AssetImage kD() {
        return AssetImage(asset.kD.keyName);
      }
  /// asset: assets/images/solitaire/KH.png
      // ignore: non_constant_identifier_names
      AssetImage kH() {
        return AssetImage(asset.kH.keyName);
      }
  /// asset: assets/images/solitaire/KS.png
      // ignore: non_constant_identifier_names
      AssetImage kS() {
        return AssetImage(asset.kS.keyName);
      }
  /// asset: assets/images/solitaire/QC.png
      // ignore: non_constant_identifier_names
      AssetImage qC() {
        return AssetImage(asset.qC.keyName);
      }
  /// asset: assets/images/solitaire/QD.png
      // ignore: non_constant_identifier_names
      AssetImage qD() {
        return AssetImage(asset.qD.keyName);
      }
  /// asset: assets/images/solitaire/QH.png
      // ignore: non_constant_identifier_names
      AssetImage qH() {
        return AssetImage(asset.qH.keyName);
      }
  /// asset: assets/images/solitaire/QS.png
      // ignore: non_constant_identifier_names
      AssetImage qS() {
        return AssetImage(asset.qS.keyName);
      }
  /// asset: assets/images/solitaire/TC.png
      // ignore: non_constant_identifier_names
      AssetImage tC() {
        return AssetImage(asset.tC.keyName);
      }
  /// asset: assets/images/solitaire/TD.png
      // ignore: non_constant_identifier_names
      AssetImage tD() {
        return AssetImage(asset.tD.keyName);
      }
  /// asset: assets/images/solitaire/TH.png
      // ignore: non_constant_identifier_names
      AssetImage tH() {
        return AssetImage(asset.tH.keyName);
      }
  /// asset: assets/images/solitaire/TS.png
      // ignore: non_constant_identifier_names
      AssetImage tS() {
        return AssetImage(asset.tS.keyName);
      }
  /// asset: assets/images/solitaire/joker.png
      // ignore: non_constant_identifier_names
      AssetImage joker() {
        return AssetImage(asset.joker.keyName);
      }
  /// asset: assets/images/transparent_background.jpg
      // ignore: non_constant_identifier_names
      AssetImage transparent_background_jpg() {
        return AssetImage(asset.transparent_background_jpg.keyName);
      }
    }
/// This `_R_Svg` class is generated and contains references to static svg type image asset resources.
    // ignore: camel_case_types
    class _R_Svg {
      const _R_Svg();
    
      final asset = const _R_Svg_AssetResource();
    
    }
/// This `_R_Text` class is generated and contains references to static text asset resources.
    // ignore: camel_case_types
    class _R_Text {
      const _R_Text();
    
      final asset = const _R_Text_AssetResource();
    
    }
/// This `_R_FontFamily` class is generated and contains references to static font asset resources.
    // ignore: camel_case_types
    class _R_FontFamily {
      const _R_FontFamily();
    
    }